# Generated by Django 5.1.1 on 2024-09-20 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Obligatoire. 255 caractères ou moins. Lettres, chiffres et espaces uniquement', max_length=255, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(help_text='Obligatoire. 255 caractères ou moins. Lettres, chiffres, @ uniquement', max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text="L'utilisateur est actif", verbose_name='Est actif')),
                ('is_superuser', models.BooleanField(default=False, help_text='Est un super utilisateur', verbose_name='Est un superuser')),
                ('is_staff', models.BooleanField(default=False, help_text="Fait parti de l'équipe d'administration", verbose_name='Est un admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Le titre doit être brêf', max_length=255, verbose_name='Titre')),
                ('details', models.TextField(help_text='Donnez des détails de votre tache', verbose_name='Details')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='La date de création de la tache', verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
